### ISSUE TITLE
Idiom and API Use

### ISSUE THREAD

**Issue by jbarnette** [ingoweiss/gem_patching#2]
Neat idea. As a RubyGems maintainer, a few things you might want to tweak come to mind:
- This isn't the normal file structure or gem name for a RubyGems (or any other well-behaved gem) plugin. If you'd like to follow our standard naming convention, the gem would be called `gem-patching` (dash, not underscore) and the code would live in `lib/rubygems/patching.rb`.
- Consider changing the `patching` method's signature to `patching(name, *requirements)`, using those arguments to create a `Gem::Dependency`, and using `Gem.available?` to check for your gem. This would allow use of all of RubyGems' normal version specifiers.
- Consider showing a warning when the patch isn't going to be applied rather than raising an error.

**Comment by ingoweiss** [comment]
Thanks a lot for your suggestions - I will look into implementing them as soon as I have a chance!

**Comment by ingoweiss** [comment]
I renamed the gem to 'gem-patching' and implemented the support for the rubygems dependency syntax. It looked like 'Gem.available?' checks against all _available_ gems, not the active ones, so I did this instead:

```
def self.patching(name, *requirements, &block)
  target = Gem::Dependency.new(name, *requirements)
  loaded_gem = Gem.loaded_specs[name]
  if loaded_gem && target.requirement.satisfied_by?(loaded_gem.version)
    ...
  end
end
```

is this the right way to do this?

**Comment by jbarnette** [comment]
Yup, that's great. I'll be adding `Gem.activated?` to the next version of RubyGems to cover this case.
